server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myempdb
    username: root
    password: root
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#logs select,create,update,delete statements
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    #org.springframework: DEBUG

